"""End-to-end client onboarding walkthrough.

Simulates onboarding a brand-new accounting firm client through the
full document/PM system:

    1. Validate the SharePoint site definition
    2. Provision a new client + 3 initial matters (tax + q3 + advisory)
    3. Run the Power Automate approval flow on the seed deliverables
    4. Answer 3 Copilot-style queries about the new client

Writes `client-onboarding-report.md` in the current directory with the
full markdown report suitable for handing to the practice manager.

Run:
    python examples/onboard_client.py
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from accounting_doc_mgmt.approval_flow import run_approval_flow
from accounting_doc_mgmt.backend import Client, MockSharePoint, NOW
from accounting_doc_mgmt.copilot_index import answer_query
from accounting_doc_mgmt.matter_provisioner import MatterSpec, provision_matter
from accounting_doc_mgmt.site_definition import DEFAULT_SITE, validate_site_definition


REPORT_PATH = Path("client-onboarding-report.md")
NEW_CLIENT = Client(
    id="c-11",
    name="Kaminski Auto Repair",
    kind="small_business",
    industry="automotive",
    partner_upn="sarah.jones@acmecpas.onmicrosoft.com",
)


def build_report() -> str:
    parts: list[str] = []
    parts.append(f"# Client onboarding report: {NEW_CLIENT.name}")
    parts.append("")
    parts.append("*Generated by the `accounting-doc-mgmt` kit end-to-end walkthrough. "
                 "In a real engagement this runs against your live SharePoint tenant via "
                 "`GRAPH_BACKEND=graph`.*")
    parts.append("")

    # Phase 1: validate site
    parts.append("## 1. Site definition validation")
    parts.append("")
    issues = validate_site_definition(DEFAULT_SITE)
    if not issues:
        parts.append(f"Site `{DEFAULT_SITE.site_name}` valid: "
                     f"{len(DEFAULT_SITE.libraries)} libraries, "
                     f"{len(DEFAULT_SITE.roles)} roles.")
        for lib in DEFAULT_SITE.libraries:
            parts.append(f"- **{lib.name}** ({len(lib.metadata_columns)} metadata columns, "
                         f"{lib.retention_years}y retention"
                         + (f", approvals: {', '.join(lib.approval_required_for)}" if lib.approval_required_for else "")
                         + ")")
    else:
        parts.append("**Validation issues:**")
        for iss in issues:
            parts.append(f"- {iss}")
    parts.append("")

    # Phase 2: register client + provision 3 matters
    backend = MockSharePoint()
    backend._clients.append(NEW_CLIENT)

    parts.append(f"## 2. Client + matters provisioned")
    parts.append("")
    parts.append(f"**Client:** {NEW_CLIENT.name} ({NEW_CLIENT.kind}, {NEW_CLIENT.industry})")
    parts.append(f"**Partner:** {NEW_CLIENT.partner_upn}")
    parts.append("")

    matter_specs = [
        MatterSpec(
            matter_id="m-11-tax-2026", client_id="c-11", kind="tax_return", year=2026,
            partner_upn=NEW_CLIENT.partner_upn,
            senior_upn="raj.patel@acmecpas.onmicrosoft.com",
            staff_upns=["tyler.brooks@acmecpas.onmicrosoft.com"],
            client_reviewer_upn="owner@kaminski-auto.com",
            due_date=datetime(2027, 4, 15, tzinfo=timezone.utc),
        ),
        MatterSpec(
            matter_id="m-11-q3-2026", client_id="c-11", kind="quarterly_review", year=2026,
            partner_upn=NEW_CLIENT.partner_upn,
            senior_upn="raj.patel@acmecpas.onmicrosoft.com",
            staff_upns=["tyler.brooks@acmecpas.onmicrosoft.com"],
            due_date=NOW + timedelta(days=45),
        ),
        MatterSpec(
            matter_id="m-11-advisory-2026", client_id="c-11", kind="advisory", year=2026,
            partner_upn=NEW_CLIENT.partner_upn,
            senior_upn="raj.patel@acmecpas.onmicrosoft.com",
            due_date=NOW + timedelta(days=30),
        ),
    ]

    provision_results = []
    for spec in matter_specs:
        result = provision_matter(spec, backend)
        provision_results.append(result)
        parts.append(f"### {spec.matter_id} - {spec.kind.replace('_', ' ')}")
        parts.append("")
        parts.append(f"- Due date: {spec.due_date.date()}")
        parts.append(f"- Folders created: {len(result.folders_created)}")
        parts.append(f"- Seed documents: {len(result.documents_seeded)}")
        parts.append(f"- Permissions set: {len(result.permissions_set)} "
                     f"({', '.join(sorted({p.role for p in result.permissions_set}))})")
        parts.append("")

    # Phase 3: run approval flow on Q3 matter's workpapers
    parts.append("## 3. Power Automate approval flow simulation")
    parts.append("")
    parts.append("Simulating the approval flow on the Q3 quarterly-review matter's seed workpaper.")
    parts.append("")
    flow_summary = run_approval_flow(backend, matter_id="m-11-q3-2026")
    parts.append(f"**{flow_summary.summary()}**")
    parts.append("")
    for run in flow_summary.runs:
        parts.append(f"- Doc `{run.document_id}`: **{run.final_status}** "
                     f"(retries={run.retries})")
        for step in run.steps:
            parts.append(f"  - {step.step_name} by `{step.approver_upn}` -> "
                         f"{step.decision.value.upper()}")
    parts.append("")

    # Phase 4: Copilot queries
    parts.append("## 4. Copilot queries")
    parts.append("")
    queries = [
        f"What's the status of matter m-11-tax-2026?",
        f"Which matters are due in the next 60 days?",
        f"Show me documents for {NEW_CLIENT.name} that haven't been signed off",
    ]
    for q in queries:
        ans = answer_query(q, backend)
        parts.append(f"### Q: {q}")
        parts.append("")
        parts.append(f"**Intent:** `{ans.intent}`")
        parts.append("")
        for line in ans.answer.split("\n"):
            parts.append(f"- {line}")
        parts.append("")

    parts.append("---")
    parts.append("")
    parts.append("**Handover checklist:**")
    parts.append("")
    parts.append(f"- [ ] Client welcome email sent to {NEW_CLIENT.partner_upn}")
    parts.append("- [ ] Client portal invite delivered to `owner@kaminski-auto.com`")
    parts.append("- [ ] Retention policies verified per library")
    parts.append("- [ ] Approval flow tested against a real deliverable")
    parts.append("- [ ] Copilot query layer indexed against the new matter metadata")
    parts.append("")

    return "\n".join(parts)


def main() -> int:
    report = build_report()
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}  ({len(report.splitlines())} lines)")
    print()
    print("First 40 lines:")
    print()
    for line in report.splitlines()[:40]:
        print(line)
    print()
    print("...")
    print(f"(full report at {REPORT_PATH})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
